apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/abhyudaya01/healthcare-backend
        env:
        - name: MONGO_HOST
          value: mongo.healthcare.svc.cluster.local
        resources:
        ports:
        - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001

